[env]
TERM = "tmux-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "none"

dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
# option_as_alt = "Both"
# opacity               = 0.95
# blur                  = true
padding = { x = 0, y = 0 }

[scrolling]
history = 0

[cursor]
blink_interval = 500
style = { shape = "Block" }
